kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: acm-readers
  annotations:
    configmanagement.gke.io/cluster-selector: selector-aws
subjects:
- kind: ServiceAccount
  name: connect-user
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: acm-reader
  apiGroup: rbac.authorization.k8s.io
