kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: acm-readers
  annotations:
    configmanagement.gke.io/cluster-selector: selector-on-prem
subjects:
- kind: Group
  name: 35121455-adcd-4189-85d2-196756b4c9cf
roleRef:
  kind: ClusterRole
  name: acm-reader
  apiGroup: rbac.authorization.k8s.io
